services:
  postgres-db-users:
    container_name: postgresDbUsers
    image: postgres:16.0
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - '25432:5432'
    volumes:
      - postgres-data-users:/var/lib/postgresql/data
    networks:
      - shared

volumes:
  postgres-data-users:

networks:
  shared:
